# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='tuition',
            field=models.FloatField(default=0.0),
        ),
    ]
