# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20171112_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Majors',
            new_name='Major',
        ),
    ]
