# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20171112_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='school',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
