# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20171112_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='school_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
    ]
