# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20171113_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='school',
        ),
        migrations.AddField(
            model_name='major',
            name='school',
            field=models.ManyToManyField(default=1, to='schools.School'),
        ),
    ]
